#!/usr/bin/env bash

# shellcheck disable=SC1091,SC2034,SC2016
PROMPT='%{$fg[blue]%}<-%{$fg_bold[blue]%} %! $(prompt_char) $(git_time_since_commit) $(git_prompt_status) ${return_status}%{$reset_color%}
%{$fg_bold[green]%}%n@%m %{$fg[blue]%}%D{[%H:%M:%S]} %{$reset_color%}%{$fg[white]%}[%~]%{$reset_color%}$(git_prompt_short_sha)$(git_prompt_info)
%{$fg[blue]%}->%{$fg_bold[blue]%} %#%{$reset_color%} '
RPROMPT=""

source "$HOME/.profile"

export CLICOLOR=1
export SYSTEMD_EDITOR="vim"

function update_nvm {
    (
        cd "$NVM_DIR" || exit
        git fetch --tags origin
        git checkout "$(git describe --abbrev=0 --tags --match "v[0-9]*" "$(git rev-list --tags --max-count=1)")"
    )
}

function pyenvr {
    (
        eval "$(pyenv init -)"
        IS_FIRST_ARG_V=1
        echo "$1" | grep -qE '[0-9]+\.[0-9]+' || echo "$1" | grep -qE '[0-9]+' || IS_FIRST_ARG_V=0
        if [ "$IS_FIRST_ARG_V" -eq "1" ]; then
            pyenv shell "$1" && shift && pyenv exec "$@"
        else
            pyenv exec "$@"
        fi
    )
}

function envupdate_ {
    command -v env-update >/dev/null && env-update
    source /etc/profile
    # [[ "$OSTYPE" != "darwin"* ]] && echo macos
    [ -n "$ZSH_NAME" ] && source "$HOME/.zshrc"
    [ -n "$BASH" ] && source "$HOME/.bashrc"
    command -v rehash >/dev/null && rehash
}

alias rt='tput reset'
alias aria2c_='aria2c --no-conf --file-allocation=none -x 16 -c'

[ -r "$HOME/.custom-shellrc" ]  && source "$HOME/.custom-shellrc"