#!/usr/bin/env bash

append-path- () {
  case ":$PATH:" in
    *:"$1":*) ;;
    *)
      PATH="$1${PATH:+:$PATH}"
      ;;
    esac
}

# nvm
NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" && export NVM_DIR
[ -d "$NVM_DIR/versions/node" ] && {
    NVM_LATEST_V=$(find "$NVM_DIR/versions/node" -mindepth 1 -maxdepth 1 -type d | sed 's:.*/::g' | sort -rV | head -n 1)
}
[ -n "$NVM_LATEST_V" ] && {
    append-path- "$NVM_DIR/versions/node/$NVM_LATEST_V/bin" && export PATH
}
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh" --no-use
unset NVM_LATEST_V

# rbenv
command -v rbenv >/dev/null && {
    case ":$PATH:" in
    *":$HOME/.rbenv/shims:"*) ;;
    *)
        if [[ -n "$ZSH_NAME" ]]; then
            eval "$(rbenv init - zsh)"
        elif [[ -n "$BASH" ]]; then
            eval "$(rbenv init - bash)"
        else
            eval "$(rbenv init -)"
        fi
        ;;
    esac
}

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
append-path- "$PYENV_ROOT/bin" && export PATH
command -v pyenv &>/dev/null && eval "$(pyenv init -)"

# pixi
append-path- "$HOME/.pixi/bin" && export PATH

# cargo
append-path- "$HOME/.cargo/bin" && export PATH

# $HOME/.local/bin
append-path- "$HOME/.local/bin" && export PATH

# go
append-path- "$HOME/go/bin" && export PATH

# /usr/local/sbin
append-path- "/usr/local/sbin" && export PATH

# sdkman
export SDKMAN_DIR="$HOME/.sdkman"
command -v sdk &>/dev/null || {
  [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
}

export CLICOLOR=1
export SYSTEMD_EDITOR="vim"
export EDITOR="vim"
export NODE_REPL_HISTORY=''
export PIPENV_VENV_IN_PROJECT=1
export POETRY_VIRTUALENVS_IN_PROJECT=1

unset append-path-

[ -r "$HOME/.custom-shellprofile" ] && source "$HOME/.custom-shellprofile"
